### ISSUE TITLE
failure to get repositories

### ISSUE THREAD

**Issue by 77loopin** [ReviewNB/support#125]
```
Internal Server Error: /api/v1/repo/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/org/views.py", line 234, in list
    repos = user.repos()
  File "/app/org/models.py", line 147, in repos
    result.extend(installation.repos())
  File "/app/org/models.py", line 255, in repos
    repos = json.loads(response.text)['repositories']
KeyError: 'repositories'
```

I'm using on-premise reviewnb.
When I access reviewnb page, the error occurred. the error doesn't occur for some of users.
How can I debug this error?

**Comment by amit1rrr** [comment]
For self-hosted ReviewNB support - please write an email to **support@reviewnb.com** from your company email address.

Closing this here. When you write an email, we'll open new ticket on our internal tracker.
